live_config_reload = false
ipc_socket = false

# Colors (BlulocoDark)
[colors.bright]
black = '#8f9aae'
blue = '#10b1fe'
cyan = '#5fb9bc'
green = '#3fc56b'
magenta = '#ff78f8'
red = '#ff6480'
white = '#ffffff'
yellow = '#f9c859'

[colors.normal]
black = '#41444d'
blue = '#3476ff'
cyan = '#4483aa'
green = '#25a45c'
magenta = '#7a82da'
red = '#fc2f52'
white = '#cdd4e0'
yellow = '#ff936a'

[colors.primary]
background = '#282c34'
foreground = '#b9c0cb'

[colors.cursor]
cursor = '#ffcc00'
text = '#282c34'

[colors.selection]
background = '#b9c0ca'
text = '#272b33'

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 20.0

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[shell]
program = "/bin/zsh"

[window]
decorations = "full"
decorations_theme_variant = "dark"
dynamic_title = false
opacity = 1.0
title = "glhfggwp"

[window.dimensions]
columns = 80
lines = 25

[window.position]
x = 0
y = 0

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
