vim.g.tokyonight_style = 'storm'
vim.g.tokyonight_terminal_colors = true
vim.g.tokyonight_italic_comments = true
vim.g.tokyonight_italic_keywords = true
vim.g.tokyonight_italic_functions = true
vim.g.tokyonight_italic_variables = true
vim.g.tokyonight_dark_float = true
vim.g.tokyonight_day_brightness = 0.3
pcall(vim.cmd, [[colorscheme tokyonight]])
